DROP TABLE purchase_history CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying (20),
    password character varying(20),
    age int, birth_date date, createdAt date
);

CREATE TABLE IF NOT EXISTS purchase_history (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int, FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS operation (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sum decimal, date date, type character varying(20),
    purchase_history integer, FOREIGN KEY (purchase_history) REFERENCES purchase_history(id)
);