version: '3.9'

services:
  postgres:
    container_name: pg
    image: postgres:13.3
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: purchaseHistoryApp
      PGPORT: 5435
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    networks:
      - spring-cloud-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - spring-cloud-network

  kafka:
    container_name: kafka
    depends_on:
    - zookeeper
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spring-cloud-network

  first-history-app:
    container_name: first-history-app
    build:
      context: ../history
      dockerfile: ./Dockerfile
    image: history-app:latest
    environment:
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_URL: jdbc:postgresql://pg:5435/purchaseHistoryApp
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: sa
      DATABASE_DIALECT: org.hibernate.dialect.PostgreSQL9Dialect
    ports:
      - "8084:8084"
    networks:
      - spring-cloud-network

  second-history-app:
    container_name: second-history-app
    build:
      context: ../history
      dockerfile: ./Dockerfile
    image: history-app:latest
    environment:
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_URL: jdbc:postgresql://pg:5435/purchaseHistoryApp
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: sa
      DATABASE_DIALECT: org.hibernate.dialect.PostgreSQL9Dialect
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network

  operations-app:
    container_name: operations-app
    build:
      context: ../operations
      dockerfile: ./Dockerfile
    image: operations-app:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network

  generator-app:
    container_name: generator-app
    build:
      context: ../generator
      dockerfile: ./Dockerfile
    image: generator-app:latest
    ports:
      - "8087:8087"
    networks:
      - spring-cloud-network

  load-app:
    container_name: load-app
    build:
      context: ../load
      dockerfile: ./Dockerfile
    image: load-app:latest
    ports:
      - "8089:8089"
    networks:
    - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
