DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying (20),
    password character varying(20),
    age int, birth_date date, createdAt date
);

CREATE TABLE IF NOT EXISTS purchase_history (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int, FOREIGN KEY (user_id) REFERENCES users(id)
)